/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLayoutFooter: typeof import('./../components/layouts/Footer/base-layout-footer.vue')['default']
    BaseLayoutHeader: typeof import('./../components/layouts/Header/base-layout-header.vue')['default']
    BaseLayoutSide: typeof import('./../components/layouts/Aside/base-layout-side.vue')['default']
    BaseUiCard: typeof import('./../components/base/base-ui-card.vue')['default']
    DictionaryManagent: typeof import('./../components/business/Setting/DictionaryManagent.vue')['default']
    DictionaryManagentAddDictionary: typeof import('./../views/Setting/DictionaryManagent/dictionary-managent-add-dictionary.vue')['default']
    DictionaryManagentDictionaryItem: typeof import('./../views/Setting/DictionaryManagent/dictionary-managent-dictionary-item.vue')['default']
    DictionaryManagentEditDictionary: typeof import('./../views/Setting/DictionaryManagent/dictionary-managent-edit-dictionary.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    HeaderMenuCollapseBtn: typeof import('./../components/layouts/Header/header-menu-collapse-btn.vue')['default']
    HeaderNavigatorBar: typeof import('./../components/layouts/Header/header-navigator-bar.vue')['default']
    HeaderTabItem: typeof import('./../components/layouts/Header/header-tab-item.vue')['default']
    HeaderTabs: typeof import('./../components/layouts/Header/header-tabs.vue')['default']
    HeaderToolBar: typeof import('./../components/layouts/Header/header-tool-bar.vue')['default']
    HeaderUserOperationBar: typeof import('./../components/layouts/Header/header-user-operation-bar.vue')['default']
    IcomDemoDemo: typeof import('./../components/icons/IcomDemoDemo.vue')['default']
    IconAvatar: typeof import('./../components/icons/IconAvatar.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDark: typeof import('./../components/icons/IconDark.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconLight: typeof import('./../components/icons/IconLight.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    IconVue: typeof import('./../components/icons/IconVue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePagenation: typeof import('./../components/base/table-pagenation.vue')['default']
    UserRegister: typeof import('./../views/Login/user-register.vue')['default']
    Welcome: typeof import('./../views/home/home-page/Welcome.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
