/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, '//Components' | '//Components/IconList' | '//Home' | '//Home/DashBoard' | '//Home/Demo' | '//Home/HomePage' | '//Setting' | '//Setting/DepartmentManagement' | '//Setting/DictionaryManagement' | '//Setting/EmployeeManagement' | '//Setting/MenuManagement' | '//Setting/ProfileManagement' | '//Setting/TaskManagement'>,
    '//Components': RouteRecordInfo<'//Components', '/Components', Record<never, never>, Record<never, never>, '//Components/IconList'>,
    '//Components/IconList': RouteRecordInfo<'//Components/IconList', '/Components/IconList', Record<never, never>, Record<never, never>>,
    '//Home': RouteRecordInfo<'//Home', '/Home', Record<never, never>, Record<never, never>, '//Home/DashBoard' | '//Home/Demo' | '//Home/HomePage'>,
    '//Home/DashBoard': RouteRecordInfo<'//Home/DashBoard', '/Home/DashBoard', Record<never, never>, Record<never, never>>,
    '//Home/Demo': RouteRecordInfo<'//Home/Demo', '/Home/Demo', Record<never, never>, Record<never, never>>,
    '//Home/HomePage': RouteRecordInfo<'//Home/HomePage', '/Home/HomePage', Record<never, never>, Record<never, never>>,
    '//Setting': RouteRecordInfo<'//Setting', '/Setting', Record<never, never>, Record<never, never>, '//Setting/DepartmentManagement' | '//Setting/DictionaryManagement' | '//Setting/EmployeeManagement' | '//Setting/MenuManagement' | '//Setting/ProfileManagement' | '//Setting/TaskManagement'>,
    '//Setting/DepartmentManagement': RouteRecordInfo<'//Setting/DepartmentManagement', '/Setting/DepartmentManagement', Record<never, never>, Record<never, never>>,
    '//Setting/DictionaryManagement': RouteRecordInfo<'//Setting/DictionaryManagement', '/Setting/DictionaryManagement', Record<never, never>, Record<never, never>>,
    '//Setting/EmployeeManagement': RouteRecordInfo<'//Setting/EmployeeManagement', '/Setting/EmployeeManagement', Record<never, never>, Record<never, never>>,
    '//Setting/MenuManagement': RouteRecordInfo<'//Setting/MenuManagement', '/Setting/MenuManagement', Record<never, never>, Record<never, never>>,
    '//Setting/ProfileManagement': RouteRecordInfo<'//Setting/ProfileManagement', '/Setting/ProfileManagement', Record<never, never>, Record<never, never>>,
    '//Setting/TaskManagement': RouteRecordInfo<'//Setting/TaskManagement', '/Setting/TaskManagement', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
  }
}
