/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, '//' | '//Home' | '//Home/' | '//Home/DashBoard' | '//Home/HomePage' | '//Setting' | '//Setting/' | '//Setting/DepartmentMangement' | '//Setting/MenuMangement' | '//Setting/Profile' | '//Setting/TaskMangement'>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//Home': RouteRecordInfo<'//Home', '/Home', Record<never, never>, Record<never, never>, '//Home/' | '//Home/DashBoard' | '//Home/HomePage'>,
    '//Home/': RouteRecordInfo<'//Home/', '/Home', Record<never, never>, Record<never, never>>,
    '//Home/DashBoard': RouteRecordInfo<'//Home/DashBoard', '/Home/DashBoard', Record<never, never>, Record<never, never>>,
    '//Home/HomePage': RouteRecordInfo<'//Home/HomePage', '/Home/HomePage', Record<never, never>, Record<never, never>>,
    '//Setting': RouteRecordInfo<'//Setting', '/Setting', Record<never, never>, Record<never, never>, '//Setting/' | '//Setting/DepartmentMangement' | '//Setting/MenuMangement' | '//Setting/Profile' | '//Setting/TaskMangement'>,
    '//Setting/': RouteRecordInfo<'//Setting/', '/Setting', Record<never, never>, Record<never, never>>,
    '//Setting/DepartmentMangement': RouteRecordInfo<'//Setting/DepartmentMangement', '/Setting/DepartmentMangement', Record<never, never>, Record<never, never>>,
    '//Setting/MenuMangement': RouteRecordInfo<'//Setting/MenuMangement', '/Setting/MenuMangement', Record<never, never>, Record<never, never>>,
    '//Setting/Profile': RouteRecordInfo<'//Setting/Profile', '/Setting/Profile', Record<never, never>, Record<never, never>>,
    '//Setting/TaskMangement': RouteRecordInfo<'//Setting/TaskMangement', '/Setting/TaskMangement', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
  }
}
