export default [
  {
    value: '中国',
    label: '中国',
    children: [
      {
        value: 'beijing',
        label: '北京',
        children: [
          {
            value: 'office-1-10',
            label: '办公室1-10层',
            children: [
              { value: '1A-2F', label: '1A-2F' },
              { value: '3B-4C', label: '3B-4C' },
              { value: '5D-6E', label: '5D-6E' },
              { value: '7F-8A', label: '7F-8A' },
              { value: '9B-0C', label: '9B-0C' },
              { value: 'A1-B2', label: 'A1-B2' },
              { value: 'C3-D4', label: 'C3-D4' },
            ],
          },
          {
            value: 'office-2-15',
            label: '办公室2-15层',
            children: [
              { value: 'E5-F6', label: 'E5-F6' },
              { value: 'G7-H8', label: 'G7-H8' },
              { value: 'I9-J0', label: 'I9-J0' },
              { value: 'K1-L2', label: 'K1-L2' },
              { value: 'M3-N4', label: 'M3-N4' },
              { value: 'O5-P6', label: 'O5-P6' },
              { value: 'Q7-R8', label: 'Q7-R8' },
              { value: 'S9-T0', label: 'S9-T0' },
            ],
          },
          {
            value: 'office-3-20',
            label: '办公室3-20层',
            children: [
              { value: 'U1-V2', label: 'U1-V2' },
              { value: 'W3-X4', label: 'W3-X4' },
              { value: 'Y5-Z6', label: 'Y5-Z6' },
              { value: 'A7-B8', label: 'A7-B8' },
              { value: 'C9-D0', label: 'C9-D0' },
              { value: 'E1-F2', label: 'E1-F2' },
              { value: 'G3-H4', label: 'G3-H4' },
            ],
          },
        ],
      },
      {
        value: 'shanghai',
        label: '上海',
        children: [
          {
            value: 'office-1-8',
            label: '办公室1-8层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: 'office-2-12',
            label: '办公室2-12层',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
        ],
      },
      {
        value: 'shenzhen',
        label: '深圳',
        children: [
          {
            value: 'office-1-5',
            label: '办公室1-5层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: 'office-2-8',
            label: '办公室2-8层',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
            ],
          },
          {
            value: 'office-3-15',
            label: '办公室3-15层',
            children: [
              { value: 'SC-TD', label: 'SC-TD' },
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
            ],
          },
        ],
      },
      {
        value: 'guangzhou',
        label: '广州',
        children: [
          {
            value: 'office-1-6',
            label: '办公室1-6层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '美国',
    label: '美国',
    children: [
      {
        value: 'newyork',
        label: '纽约',
        children: [
          {
            value: 'office-1-30',
            label: '办公室1-30层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
          {
            value: 'office-2-40',
            label: '办公室2-40层',
            children: [
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
          {
            value: 'office-3-50',
            label: '办公室3-50层',
            children: [
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
            ],
          },
        ],
      },
      {
        value: 'losangeles',
        label: '洛杉矶',
        children: [
          {
            value: 'office-1-20',
            label: '办公室1-20层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: 'office-2-25',
            label: '办公室2-25层',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
        ],
      },
      {
        value: 'chicago',
        label: '芝加哥',
        children: [
          {
            value: 'office-1-15',
            label: '办公室1-15层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: 'office-2-18',
            label: '办公室2-18层',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
            ],
          },
          {
            value: 'office-3-22',
            label: '办公室3-22层',
            children: [
              { value: 'SC-TD', label: 'SC-TD' },
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
        ],
      },
      {
        value: 'sanfrancisco',
        label: '旧金山',
        children: [
          {
            value: 'office-1-12',
            label: '办公室1-12层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '马来西亚',
    label: '马来西亚',
    children: [
      {
        value: 'kualalumpur',
        label: '吉隆坡',
        children: [
          {
            value: 'office-1-8',
            label: '办公室1-8层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
          {
            value: 'office-2-12',
            label: '办公室2-12层',
            children: [
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
          {
            value: 'office-3-15',
            label: '办公室3-15层',
            children: [
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
            ],
          },
        ],
      },
      {
        value: 'penang',
        label: '槟城',
        children: [
          {
            value: 'office-1-6',
            label: '办公室1-6层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: 'office-2-9',
            label: '办公室2-9层',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
            ],
          },
        ],
      },
      {
        value: 'johorbahru',
        label: '新山',
        children: [
          {
            value: 'office-1-5',
            label: '办公室1-5层',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: 'office-2-7',
            label: '办公室2-7层',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
          {
            value: 'office-3-10',
            label: '办公室3-10层',
            children: [
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
        ],
      },
    ],
  },
]
