export default [
  {
    value: '中国',
    label: '中国',
    children: [
      {
        value: 'beijing',
        label: '北京',
        children: [
          {
            value: '办公室 10F',
            label: '办公室 10F',
            children: [
              { value: '1A-2F', label: '1A-2F' },
              { value: '3B-4C', label: '3B-4C' },
              { value: '5D-6E', label: '5D-6E' },
              { value: '7F-8A', label: '7F-8A' },
              { value: '9B-0C', label: '9B-0C' },
              { value: 'A1-B2', label: 'A1-B2' },
              { value: 'C3-D4', label: 'C3-D4' },
            ],
          },
          {
            value: '办公室 15F',
            label: '办公室 15F',
            children: [
              { value: 'E5-F6', label: 'E5-F6' },
              { value: 'G7-H8', label: 'G7-H8' },
              { value: 'I9-J0', label: 'I9-J0' },
              { value: 'K1-L2', label: 'K1-L2' },
              { value: 'M3-N4', label: 'M3-N4' },
              { value: 'O5-P6', label: 'O5-P6' },
              { value: 'Q7-R8', label: 'Q7-R8' },
              { value: 'S9-T0', label: 'S9-T0' },
            ],
          },
          {
            value: '办公室 20F',
            label: '办公室 20F',
            children: [
              { value: 'U1-V2', label: 'U1-V2' },
              { value: 'W3-X4', label: 'W3-X4' },
              { value: 'Y5-Z6', label: 'Y5-Z6' },
              { value: 'A7-B8', label: 'A7-B8' },
              { value: 'C9-D0', label: 'C9-D0' },
              { value: 'E1-F2', label: 'E1-F2' },
              { value: 'G3-H4', label: 'G3-H4' },
            ],
          },
        ],
      },
      {
        value: 'shanghai',
        label: '上海',
        children: [
          {
            value: '办公室 8F',
            label: '办公室 8F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '办公室 12F',
            label: '办公室 12F',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
        ],
      },
      {
        value: 'shenzhen',
        label: '深圳',
        children: [
          {
            value: '办公室 5F',
            label: '办公室 5F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '办公室 8F',
            label: '办公室 8F',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
            ],
          },
          {
            value: '办公室 15F',
            label: '办公室 15F',
            children: [
              { value: 'SC-TD', label: 'SC-TD' },
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
            ],
          },
        ],
      },
      {
        value: '济南',
        label: '济南',
        children: [
          {
            value: '济南CBD办公室 2F',
            label: '济南CBD办公室 2F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '济南CBD办公室 3F',
            label: '济南CBD办公室 3F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '美国',
    label: '美国',
    children: [
      {
        value: 'newyork',
        label: '纽约',
        children: [
          {
            value: '办公室 30F',
            label: '办公室 30F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
          {
            value: '办公室 40F',
            label: '办公室 40F',
            children: [
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
          {
            value: '办公室 50F',
            label: '办公室 50F',
            children: [
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
            ],
          },
        ],
      },
      {
        value: 'losangeles',
        label: '洛杉矶',
        children: [
          {
            value: '办公室 20F',
            label: '办公室 20F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '办公室 25F',
            label: '办公室 25F',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
        ],
      },
      {
        value: 'chicago',
        label: '芝加哥',
        children: [
          {
            value: '办公室 15F',
            label: '办公室 15F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '办公室 18F',
            label: '办公室 18F',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
            ],
          },
          {
            value: '办公室 22F',
            label: '办公室 22F',
            children: [
              { value: 'SC-TD', label: 'SC-TD' },
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
        ],
      },
      {
        value: 'sanfrancisco',
        label: '旧金山',
        children: [
          {
            value: '办公室 12F',
            label: '办公室 12F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '马来西亚',
    label: '马来西亚',
    children: [
      {
        value: 'kualalumpur',
        label: '吉隆坡',
        children: [
          {
            value: '办公室 8F',
            label: '办公室 8F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
          {
            value: '办公室 12F',
            label: '办公室 12F',
            children: [
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
          {
            value: '办公室 15F',
            label: '办公室 15F',
            children: [
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
            ],
          },
        ],
      },
      {
        value: 'penang',
        label: '槟城',
        children: [
          {
            value: '办公室 6F',
            label: '办公室 6F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '办公室 9F',
            label: '办公室 9F',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
            ],
          },
        ],
      },
      {
        value: 'johorbahru',
        label: '新山',
        children: [
          {
            value: '办公室 5F',
            label: '办公室 5F',
            children: [
              { value: '1A-2B', label: '1A-2B' },
              { value: '3C-4D', label: '3C-4D' },
              { value: '5E-6F', label: '5E-6F' },
              { value: '7G-8H', label: '7G-8H' },
              { value: '9I-0J', label: '9I-0J' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
            ],
          },
          {
            value: '办公室 7F',
            label: '办公室 7F',
            children: [
              { value: 'EO-FP', label: 'EO-FP' },
              { value: 'GQ-HR', label: 'GQ-HR' },
              { value: 'IS-JT', label: 'IS-JT' },
              { value: 'KU-LV', label: 'KU-LV' },
              { value: 'MW-NX', label: 'MW-NX' },
              { value: 'OY-PZ', label: 'OY-PZ' },
              { value: 'QA-RB', label: 'QA-RB' },
              { value: 'SC-TD', label: 'SC-TD' },
            ],
          },
          {
            value: '办公室 10F',
            label: '办公室 10F',
            children: [
              { value: 'UE-VF', label: 'UE-VF' },
              { value: 'WG-XH', label: 'WG-XH' },
              { value: 'YI-ZJ', label: 'YI-ZJ' },
              { value: 'AK-BL', label: 'AK-BL' },
              { value: 'CM-DN', label: 'CM-DN' },
              { value: 'EO-FP', label: 'EO-FP' },
            ],
          },
        ],
      },
    ],
  },
]
